name: Publish Docker
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/arm64/v8,linux/amd64
          build-args:  PRESTO_VERSION=347
          tags: "digitalpatterns/presto:latest,digitalpatterns/presto:${{ github.sha }}"

